// Generated by gencpp from file usb_cam/DevicesResponse.msg
// DO NOT EDIT!


#ifndef USB_CAM_MESSAGE_DEVICESRESPONSE_H
#define USB_CAM_MESSAGE_DEVICESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usb_cam
{
template <class ContainerAllocator>
struct DevicesResponse_
{
  typedef DevicesResponse_<ContainerAllocator> Type;

  DevicesResponse_()
    : success(false)  {
    }
  DevicesResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::usb_cam::DevicesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usb_cam::DevicesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DevicesResponse_

typedef ::usb_cam::DevicesResponse_<std::allocator<void> > DevicesResponse;

typedef boost::shared_ptr< ::usb_cam::DevicesResponse > DevicesResponsePtr;
typedef boost::shared_ptr< ::usb_cam::DevicesResponse const> DevicesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usb_cam::DevicesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usb_cam::DevicesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::usb_cam::DevicesResponse_<ContainerAllocator1> & lhs, const ::usb_cam::DevicesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::usb_cam::DevicesResponse_<ContainerAllocator1> & lhs, const ::usb_cam::DevicesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace usb_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::usb_cam::DevicesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usb_cam::DevicesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usb_cam::DevicesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usb_cam::DevicesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usb_cam::DevicesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usb_cam::DevicesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usb_cam::DevicesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::usb_cam::DevicesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::usb_cam::DevicesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usb_cam/DevicesResponse";
  }

  static const char* value(const ::usb_cam::DevicesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usb_cam::DevicesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::usb_cam::DevicesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usb_cam::DevicesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DevicesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usb_cam::DevicesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usb_cam::DevicesResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USB_CAM_MESSAGE_DEVICESRESPONSE_H
