// Generated by gencpp from file usb_cam/GetFrame.msg
// DO NOT EDIT!


#ifndef USB_CAM_MESSAGE_GETFRAME_H
#define USB_CAM_MESSAGE_GETFRAME_H

#include <ros/service_traits.h>


#include <usb_cam/GetFrameRequest.h>
#include <usb_cam/GetFrameResponse.h>


namespace usb_cam
{

struct GetFrame
{

typedef GetFrameRequest Request;
typedef GetFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFrame
} // namespace usb_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::usb_cam::GetFrame > {
  static const char* value()
  {
    return "6897ffa073f098e62edfad95fcecacba";
  }

  static const char* value(const ::usb_cam::GetFrame&) { return value(); }
};

template<>
struct DataType< ::usb_cam::GetFrame > {
  static const char* value()
  {
    return "usb_cam/GetFrame";
  }

  static const char* value(const ::usb_cam::GetFrame&) { return value(); }
};


// service_traits::MD5Sum< ::usb_cam::GetFrameRequest> should match
// service_traits::MD5Sum< ::usb_cam::GetFrame >
template<>
struct MD5Sum< ::usb_cam::GetFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::usb_cam::GetFrame >::value();
  }
  static const char* value(const ::usb_cam::GetFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::usb_cam::GetFrameRequest> should match
// service_traits::DataType< ::usb_cam::GetFrame >
template<>
struct DataType< ::usb_cam::GetFrameRequest>
{
  static const char* value()
  {
    return DataType< ::usb_cam::GetFrame >::value();
  }
  static const char* value(const ::usb_cam::GetFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::usb_cam::GetFrameResponse> should match
// service_traits::MD5Sum< ::usb_cam::GetFrame >
template<>
struct MD5Sum< ::usb_cam::GetFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::usb_cam::GetFrame >::value();
  }
  static const char* value(const ::usb_cam::GetFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::usb_cam::GetFrameResponse> should match
// service_traits::DataType< ::usb_cam::GetFrame >
template<>
struct DataType< ::usb_cam::GetFrameResponse>
{
  static const char* value()
  {
    return DataType< ::usb_cam::GetFrame >::value();
  }
  static const char* value(const ::usb_cam::GetFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // USB_CAM_MESSAGE_GETFRAME_H
