// Generated by gencpp from file usb_cam/GetFrameRequest.msg
// DO NOT EDIT!


#ifndef USB_CAM_MESSAGE_GETFRAMEREQUEST_H
#define USB_CAM_MESSAGE_GETFRAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usb_cam
{
template <class ContainerAllocator>
struct GetFrameRequest_
{
  typedef GetFrameRequest_<ContainerAllocator> Type;

  GetFrameRequest_()
    {
    }
  GetFrameRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::usb_cam::GetFrameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usb_cam::GetFrameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetFrameRequest_

typedef ::usb_cam::GetFrameRequest_<std::allocator<void> > GetFrameRequest;

typedef boost::shared_ptr< ::usb_cam::GetFrameRequest > GetFrameRequestPtr;
typedef boost::shared_ptr< ::usb_cam::GetFrameRequest const> GetFrameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usb_cam::GetFrameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usb_cam::GetFrameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace usb_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::usb_cam::GetFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usb_cam::GetFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usb_cam::GetFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usb_cam::GetFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usb_cam::GetFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usb_cam::GetFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usb_cam::GetFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::usb_cam::GetFrameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::usb_cam::GetFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usb_cam/GetFrameRequest";
  }

  static const char* value(const ::usb_cam::GetFrameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usb_cam::GetFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::usb_cam::GetFrameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usb_cam::GetFrameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFrameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usb_cam::GetFrameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::usb_cam::GetFrameRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // USB_CAM_MESSAGE_GETFRAMEREQUEST_H
