// Generated by gencpp from file usb_cam/GetFrameResponse.msg
// DO NOT EDIT!


#ifndef USB_CAM_MESSAGE_GETFRAMERESPONSE_H
#define USB_CAM_MESSAGE_GETFRAMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace usb_cam
{
template <class ContainerAllocator>
struct GetFrameResponse_
{
  typedef GetFrameResponse_<ContainerAllocator> Type;

  GetFrameResponse_()
    : frame()  {
    }
  GetFrameResponse_(const ContainerAllocator& _alloc)
    : frame(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _frame_type;
  _frame_type frame;





  typedef boost::shared_ptr< ::usb_cam::GetFrameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usb_cam::GetFrameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFrameResponse_

typedef ::usb_cam::GetFrameResponse_<std::allocator<void> > GetFrameResponse;

typedef boost::shared_ptr< ::usb_cam::GetFrameResponse > GetFrameResponsePtr;
typedef boost::shared_ptr< ::usb_cam::GetFrameResponse const> GetFrameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usb_cam::GetFrameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usb_cam::GetFrameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::usb_cam::GetFrameResponse_<ContainerAllocator1> & lhs, const ::usb_cam::GetFrameResponse_<ContainerAllocator2> & rhs)
{
  return lhs.frame == rhs.frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::usb_cam::GetFrameResponse_<ContainerAllocator1> & lhs, const ::usb_cam::GetFrameResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace usb_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::usb_cam::GetFrameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usb_cam::GetFrameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usb_cam::GetFrameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usb_cam::GetFrameResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usb_cam::GetFrameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usb_cam::GetFrameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usb_cam::GetFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6897ffa073f098e62edfad95fcecacba";
  }

  static const char* value(const ::usb_cam::GetFrameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6897ffa073f098e6ULL;
  static const uint64_t static_value2 = 0x2edfad95fcecacbaULL;
};

template<class ContainerAllocator>
struct DataType< ::usb_cam::GetFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usb_cam/GetFrameResponse";
  }

  static const char* value(const ::usb_cam::GetFrameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usb_cam::GetFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image frame\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::usb_cam::GetFrameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usb_cam::GetFrameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFrameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usb_cam::GetFrameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usb_cam::GetFrameResponse_<ContainerAllocator>& v)
  {
    s << indent << "frame: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USB_CAM_MESSAGE_GETFRAMERESPONSE_H
