// Generated by gencpp from file visrun_software/etiquette.msg
// DO NOT EDIT!


#ifndef VISRUN_SOFTWARE_MESSAGE_ETIQUETTE_H
#define VISRUN_SOFTWARE_MESSAGE_ETIQUETTE_H

#include <ros/service_traits.h>


#include <visrun_software/etiquetteRequest.h>
#include <visrun_software/etiquetteResponse.h>


namespace visrun_software
{

struct etiquette
{

typedef etiquetteRequest Request;
typedef etiquetteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct etiquette
} // namespace visrun_software


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::visrun_software::etiquette > {
  static const char* value()
  {
    return "875e1933bcbc7d02f7806195e83af738";
  }

  static const char* value(const ::visrun_software::etiquette&) { return value(); }
};

template<>
struct DataType< ::visrun_software::etiquette > {
  static const char* value()
  {
    return "visrun_software/etiquette";
  }

  static const char* value(const ::visrun_software::etiquette&) { return value(); }
};


// service_traits::MD5Sum< ::visrun_software::etiquetteRequest> should match
// service_traits::MD5Sum< ::visrun_software::etiquette >
template<>
struct MD5Sum< ::visrun_software::etiquetteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::visrun_software::etiquette >::value();
  }
  static const char* value(const ::visrun_software::etiquetteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::visrun_software::etiquetteRequest> should match
// service_traits::DataType< ::visrun_software::etiquette >
template<>
struct DataType< ::visrun_software::etiquetteRequest>
{
  static const char* value()
  {
    return DataType< ::visrun_software::etiquette >::value();
  }
  static const char* value(const ::visrun_software::etiquetteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::visrun_software::etiquetteResponse> should match
// service_traits::MD5Sum< ::visrun_software::etiquette >
template<>
struct MD5Sum< ::visrun_software::etiquetteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::visrun_software::etiquette >::value();
  }
  static const char* value(const ::visrun_software::etiquetteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::visrun_software::etiquetteResponse> should match
// service_traits::DataType< ::visrun_software::etiquette >
template<>
struct DataType< ::visrun_software::etiquetteResponse>
{
  static const char* value()
  {
    return DataType< ::visrun_software::etiquette >::value();
  }
  static const char* value(const ::visrun_software::etiquetteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISRUN_SOFTWARE_MESSAGE_ETIQUETTE_H
