// Generated by gencpp from file visrun_software/etiquetteResponse.msg
// DO NOT EDIT!


#ifndef VISRUN_SOFTWARE_MESSAGE_ETIQUETTERESPONSE_H
#define VISRUN_SOFTWARE_MESSAGE_ETIQUETTERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visrun_software
{
template <class ContainerAllocator>
struct etiquetteResponse_
{
  typedef etiquetteResponse_<ContainerAllocator> Type;

  etiquetteResponse_()
    : success(false)  {
    }
  etiquetteResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::visrun_software::etiquetteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visrun_software::etiquetteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct etiquetteResponse_

typedef ::visrun_software::etiquetteResponse_<std::allocator<void> > etiquetteResponse;

typedef boost::shared_ptr< ::visrun_software::etiquetteResponse > etiquetteResponsePtr;
typedef boost::shared_ptr< ::visrun_software::etiquetteResponse const> etiquetteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visrun_software::etiquetteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visrun_software::etiquetteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visrun_software::etiquetteResponse_<ContainerAllocator1> & lhs, const ::visrun_software::etiquetteResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visrun_software::etiquetteResponse_<ContainerAllocator1> & lhs, const ::visrun_software::etiquetteResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visrun_software

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::visrun_software::etiquetteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visrun_software::etiquetteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visrun_software::etiquetteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visrun_software::etiquetteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visrun_software::etiquetteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visrun_software::etiquetteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visrun_software::etiquetteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::visrun_software::etiquetteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::visrun_software::etiquetteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visrun_software/etiquetteResponse";
  }

  static const char* value(const ::visrun_software::etiquetteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visrun_software::etiquetteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::visrun_software::etiquetteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visrun_software::etiquetteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct etiquetteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visrun_software::etiquetteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visrun_software::etiquetteResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISRUN_SOFTWARE_MESSAGE_ETIQUETTERESPONSE_H
